var u = getApp().util, a = getApp().globalData;
Page({
  data: {
    page: [
      { name: 'head', title: '公共设施' },
      { name: 'h4', text: '洗漱区' },
      { name: 'p', text: '冷水为全天供应。生活热水每日热水使用量固定为18升，且不可购买（新生需要先去激活生活热水功能才能使用。激活机器在宿舍一楼有）。本部校区上午5点到8点，晚上9点到11点供热水；净月校区上午6点到8点，晚上7点到10点供热水（天华公寓全天）.' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M00/91/62/wKjmqVl9hACAR66rAADtC1XuulU0747826/imageView/v1/thumbnail/640x0', text: '▲图为本部三舍AB洗漱区'},
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M00/91/62/wKjmqVl9g7mAbnfZAACMNWfdtg41656008/imageView/v1/thumbnail/640x0', text: '▲图为本部三舍C洗漱区' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M01/91/62/wKjmqVl9g6CAEI-WAAGVw7uu5Xs1056054/imageView/v1/thumbnail/640x0', text: '▲图为净月公寓洗漱区'},
      { name: 'h4', text: '卫生间' },
      { name: 'p', text: '卫生间处在公共区域，有阿姨定期打扫卫生，很整洁。' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M01/91/63/wKjmqVl9hXSAOBeAABmrRBrl_Q83881084/imageView/v1/thumbnail/640x0' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g2/M01/80/96/CgpQVFl9hV-ASgSHAC3XwsJHYhM9384030/imageView/v1/thumbnail/640x0' },
      { name: 'h4', text: '吹风机' },
      { name: 'p', text: '基本上女生寝室楼每层楼都有一个或两个吹风机，插一卡通就可以用。' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g2/M01/80/98/CgpQVFl9iISAW_AWAA3EFjs57wM4349529/imageView/v1/thumbnail/640x0' },
      { name: 'h4', text: '洗衣机' },
      { name: 'p', text: '>洗衣机是单筒洗衣机，可洗可甩干。大部分寝室楼的每个楼层有两个洗衣机。洗衣机为刷卡使用。刷一卡通即可。刷卡完毕将洗衣机盖关闭等待即可, 洗衣用的洗衣液或洗衣粉需自己准备，在洗衣前加入洗衣机内。' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g2/M00/80/98/CgpQVFl9iMaAY6bwAAEyJlHpDXA3713141/imageView/v1/thumbnail/640x0' },
      { name: 'h4', text: '直饮水机' },
      { name: 'p', text: '刷卡分别可以接冷/常温/热的饮用水，学校每天免费供应90秒使用时长(约2-4升，视直饮机水压)，全天供应。超出部分收取制水成本费用，热水0.3元/升，常温水0.2元/升。直饮水服务所需的额外费用，是使用校园卡小钱包内的余额，师生可以在自助终端机上进行一卡通小钱包充值。' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g2/M00/82/55/wKjmqll9iROAAyvXAAFvl0L2slU0180058/imageView/v1/thumbnail/640x0' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M00/91/68/wKjmqVl9ib2ATy4sACjJ4Roa5YQ6686464/imageView/v1/thumbnail/640x0' },
      { name: 'h4', text: '自习室' },
      { name: 'p', text: '寝室楼内每层均舍友自习室。自习室是不间断供电的。' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M00/6E/2E/CgpQU1l9jHKAFQ84AAFVHQOisPI2108104/imageView/v1/thumbnail/640x0', text: '▲图为三舍A自习室' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M01/6E/29/CgpQU1l9iciAdPf6ABhnksBE_IU0815243/imageView/v1/thumbnail/640x0', text: '▲图为三舍B自习室'  },
      { name: 'img', src: 'https://pic.kuaizhan.com/g2/M00/82/5A/wKjmqll9jC-Aa9uaAAG9IJn9V_c5121719/imageView/v1/thumbnail/640x0', text: '▲图为三舍C自习室' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g1/M01/91/68/wKjmqVl9icmAc7SrAAC8hfsXXwo9367729/imageView/v1/thumbnail/640x0', text: '▲图为天华公寓自习室'},
      { name: 'h4', text: '电梯' },
      { name: 'p', text: '三舍作为高层建筑，A座、C座拥有四台电梯，B拥有三台电梯，客梯不停低楼层，入住时可以使用货梯。净月寝室没有电梯。' },
      { name: 'img', src: 'https://pic.kuaizhan.com/g2/M00/82/5B/wKjmqll9jOGAITeNAAGlLL3dLNI6483845/imageView/v1/thumbnail/640x0' },
      { name: 'h4', text: '' },
    ],
  },
  onLoad(e) { this.setData({ T: a.T, nm: a.nm, page: u.sP(this.data.page, a, e) }) },
  onPageScroll(e) { let p = u.nav(e, this.data.page); if (p) { this.setData({ page: p }) } },
  img(e) { let p = u.img(this.data.page, e); this.setData({ page: p }) }, back() { u.back() },
})